// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUpHP6uGWzHKCtu5_vPmI1vcI7ph_Ihvk',
    appId: '1:124506192389:android:3b5d15df5a5c4ce2c33a6c',
    messagingSenderId: '124506192389',
    projectId: 'arya-30631',
    storageBucket: 'arya-30631.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUVLB1ZeR68U_FE4ib2dWuOBp2bYY-1y4',
    appId: '1:124506192389:ios:41bf9826de2537b9c33a6c',
    messagingSenderId: '124506192389',
    projectId: 'arya-30631',
    storageBucket: 'arya-30631.firebasestorage.app',
    androidClientId: '124506192389-u63mabk5mu5j8uiecnfk5rmpq874orsk.apps.googleusercontent.com',
    iosClientId: '124506192389-32s8la4ndjd5q30phqj8cnsbrht2gp67.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseEditorGsoc',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3yqOrBPY8zgkyxgX3fpaYrgxjnAyFWZQ',
    appId: '1:124506192389:web:7fcd937cc1553229c33a6c',
    messagingSenderId: '124506192389',
    projectId: 'arya-30631',
    authDomain: 'arya-30631.firebaseapp.com',
    storageBucket: 'arya-30631.firebasestorage.app',
    measurementId: 'G-QP8SDRD4SX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUVLB1ZeR68U_FE4ib2dWuOBp2bYY-1y4',
    appId: '1:124506192389:ios:41bf9826de2537b9c33a6c',
    messagingSenderId: '124506192389',
    projectId: 'arya-30631',
    storageBucket: 'arya-30631.firebasestorage.app',
    androidClientId: '124506192389-u63mabk5mu5j8uiecnfk5rmpq874orsk.apps.googleusercontent.com',
    iosClientId: '124506192389-32s8la4ndjd5q30phqj8cnsbrht2gp67.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseEditorGsoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3yqOrBPY8zgkyxgX3fpaYrgxjnAyFWZQ',
    appId: '1:124506192389:web:17314a34483c0f39c33a6c',
    messagingSenderId: '124506192389',
    projectId: 'arya-30631',
    authDomain: 'arya-30631.firebaseapp.com',
    storageBucket: 'arya-30631.firebasestorage.app',
    measurementId: 'G-FQQFFLYV0V',
  );

}